chore: nuke package-lock and reinstall because of build issue
npm error code ERR_INVALID_ARG_TYPE
npm error The "from" argument must be of type string. Received undefined
npm error A complete log of this run can be found in: /vercel/.npm/_logs/2025-10-15T13_48_46_262Z-debug-0.log
Error: Command "npm install --prefix=../.." exited with 1